### ISSUE TITLE
Different Version 이슈로 Unity 프로젝트가 열리지 않음

### ISSUE THREAD

**Issue by hsskia** [hsskia/unity_task#7]
### 문제
- Unity 두번째 과제 project 를 오픈할 때 해당 이슈 발생
  ![image](https://github.com/hsskia/unity_task/assets/162946806/890bd177-e409-4f6b-bbb4-b8fd38b1be96)

### 원인
- 프로젝트 오픈에 필요한 파일들까지 gitignore 파일에 포함시켜버림으로써 프로젝트가 열리지 않음
- 프로젝트가 열리더라도 필요 패키지가 설치되어 있지 않아서 오류 발생
- 버전 관리가 잘못되고 있음

### 해결방안
- ProjectSettings 폴더를 복구해서 ProjectVersion.txt 파일에 버전이 잘 기록되어 있는지 확인

```
m_EditorVersion: 2022.3.12f1
m_EditorVersionWithRevision: 2022.3.12f1 (4fe6e059c7ef)
```

**Comment by hsskia** [comment]
### 문제 2
- gitignore를 수정 후 프로젝트가 오픈되었지만 여전히 import 에러가 발생
- sqlite 패키지를 버전 관리에 포함하지 않아서 생겼을 것으로 추정
![image](https://github.com/hsskia/unity_task/assets/162946806/f0c70ead-73b9-4ac9-8da0-dab79a583f88)

### 해결방안
- gitignore에 기록되어 있던 Asset/Packages 폴더 복구
- 필요한 패키지들이 Asset/Packages 안에 다운로드 되어있음

**Comment by hsskia** [comment]
### 문제 3
- 위의 문제를 해결하더라도 프로젝트에서 사용한 Object 들이 보이지 않음
<img src = "https://github.com/hsskia/unity_task/assets/162946806/5c973c75-0408-4db7-b50a-c177e2abdbc7" width = "500" />

### 해결방안
- Scene 파일이 손상되어서 발생할 수 있는 문제이기 때문에 정상적인 `SampleScene.unity` 와 `SampleScene.unity.meta` 파일을 사용

**Comment by hsskia** [comment]
모든 파일들을 한번에 업로드해서 어떤 부분에서 문제가 발생했는지 파악하는게 쉽지 않았습니다. 
설치가 필요한 패키지들, 스크립트, 프로젝트 환경 등을 따로 구분해서 올리면 디버깅이 더 쉬울 것 같습니다.

**Comment by hyunheeskia** [comment]
> 모든 파일들을 한번에 업로드해서 어떤 부분에서 문제가 발생했는지 파악하는게 쉽지 않았습니다. 설치가 필요한 패키지들, 스크립트, 프로젝트 환경 등을 따로 구분해서 올리면 디버깅이 더 쉬울 것 같습니다.

네넵 그렇습니다.
commit 을 할 때
하나의 주제에 대한 내용만 들어가게 commit을 쪼갤 수 있다면 그렇게 하시는게 좋습니다.
그리고 모든 commit 에서는 diff가 없는 상태로도 build 와 실행이 되어야 하고요.
